// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpohwpzauflyygslkhmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indwb2h3cHphdWZseXlnc2xraG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1ODgxMTQsImV4cCI6MjA2NzE2NDExNH0.-a0FG6NZn44_CH92WS8XgFb2Pjg8NFvEnxwIzkh7F9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});